# docker-compose.yml
version: '3.8'
services:
  backend:
    build:
      context: ./apps/backend
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
